# apps/production/mc/patch-env.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  template:
    spec:
      containers:
        - name: mc
          env:
            - name: TYPE
              value: "AUTO_CURSEFORGE"
            - name: CF_PAGE_URL
              value: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-9"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: minecraft-env-secrets
                  key: CF_API_KEY
            - name: ICON
              value: "https://i.ibb.co/ynBjmLzB/Screenshot-2025-04-01-183257.png"
            - name: OVERRIDE_ICON
              value: "TRUE"
            - name: ALLOW_FLIGHT
              value: "TRUE"
            - name: SERVER_NAME
              value: "NecrOS"