apiVersion: v1
kind: Service
metadata:
  name: vrising-service
  labels:
    app: vrising
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: vrising
  ports:
    - protocol: UDP
      port: 9876
      targetPort: 9876
      name: udp-9876
    - protocol: UDP
      port: 9877
      targetPort: 9877
      name: udp-9877
  type: ClusterIP
