# apps/production/mc/patch-env.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  template:
    spec:
      containers:
        - name: mc
          env:
            - name: TYPE
              value: "AUTO_CURSEFORGE"
            - name: CURSEFORGE_FILES
              value: |
                butchery
                guns-plusplus
            - name: CF_PAGE_URL
              value: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-10"
            - name: CF_FILENAME_MATCHER
              value: All the Mods 10-2.44
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: minecraft-env-secrets
                  key: CF_API_KEY
            - name: ALLOW_FLIGHT
              value: "TRUE"
            - name: SERVER_NAME
              value: "NecrOS"