apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stump-config
  namespace: stump
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stump-data
  namespace: stump
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
