apiVersion: v1
kind: Service
metadata:
  name: pinky-app-backend
  labels:
    app: pinky-app-backend
spec:
  selector:
    app: pinky-app-backend
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
