---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pinky-image-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/data/pinky-images  # Make sure this exists on your nodes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silly-api-images-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pinky-image-pv
