apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinky-app-backend
spec:
  selector:
    matchLabels:
      app: pinky-app-backend
  template:
    metadata:
      labels:
        app: pinky-app-backend
    spec:
      containers:
      - name: pinky-app-backend
        image: mustybatz/silly-backend:vuwu
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: silly-api-secret
                key: my_secret.txt
          - name: WELCOME_MESSAGE
            valueFrom:
              configMapKeyRef:
                name: silly-api-config
                key: WELCOME_MESSAGE
          - name: DEFAULT_FIB_N
            valueFrom:
              configMapKeyRef:
                name: silly-api-config
                key: DEFAULT_FIB_N
          - name: DEFAULT_PI_SAMPLES
            valueFrom:
              configMapKeyRef:
                name: silly-api-config
                key: DEFAULT_PI_SAMPLES
          - name: DEFAULT_MATRIX_SIZE
            valueFrom:
              configMapKeyRef:
                name: silly-api-config
                key: DEFAULT_MATRIX_SIZE
          - name: CAT_FACTS
            valueFrom:
              configMapKeyRef:
                name: silly-api-config
                key: CAT_FACTS
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret-volume
          mountPath: /secrets
          readOnly: true
        - name: images-volume
          mountPath: /app/static
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: silly-api-secret
      - name: images-volume
        persistentVolumeClaim:
          claimName: silly-api-images-pvc
        
