apiVersion: v1
kind: Service
metadata:
  name: pinky-app-frontend
spec:
  selector:
    app: pinky-app-frontend
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: metrics
    port: 9113
    targetPort: 9113
