apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-frontend-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: pinky-app-frontend
  endpoints:
    - port: 9113
      interval: 15s
      path: /metrics
  namespaceSelector:
    any: true
