apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-frontend-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: pinky-app-frontend
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
  namespaceSelector:
    name: pinky-app
