apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudflare-operator
  namespace: cloudflare-operator-system
spec:
  interval: 5m
  url: https://github.com/adyanth/cloudflare-operator
  ref:
    branch: main
