apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-operator-system
resources:
  - cf-operator-namespace.yaml
  - cf-operator-source.yaml
  - cf-operator-kustomization.yaml
