apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pi-hole
  labels:
    name: pi-hole
  namespace: pi-hole
spec:
  rules:
  - host: pi-hole.barlabs.tech
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: pi-hole
            port: 
              number: 8080
