apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 5m
  timeout: 1m
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: "1.x"
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
  values:
    alloy:
      configMap:
        content: |-
          discovery.kubernetes "pods" {
            role = "pod"
          }

          loki.source.kubernetes "pods" {
            targets    = discovery.kubernetes.pods.targets
            forward_to = [loki.write.local.receiver]
          }

          loki.write "local" {
            endpoint {
              url = "http://loki-gateway/loki/api/v1/push"
              tenant_id = "1"
            }
          }
