apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 5m
  timeout: 1m
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: "1.x"
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
  values:
    alloy:
      configMap:
        content: |-
          logging {
            level = "debug"
            format = "logfmt"
          }

          discovery.kubernetes "pods" {
            role = "pod"
          }

          discovery.relabel "pods" {
            targets = discovery.kubernetes.pods.targets

            rule {
              source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_label_app_kubernetes_io_name", "__meta_kubernetes_pod_container_name"]
              separator     = "/"
              target_label  = "deployment_name"
              action        = "replace"
            }
          }

          loki.source.kubernetes "pods" {
            targets    = discovery.relabel.pods.output
            forward_to = [loki.process.process.receiver]
          }

          loki.process "process" {
            forward_to = [loki.write.local.receiver]

            stage.drop {
              older_than          = "1h"
              drop_counter_reason = "too old"
            }

            stage.match { 
              selector = "{instance=~\".*\"}"
              stage.json {
                expressions = {
                  level = "\"level\"",
                }
              }
              stage.labels {
                values = { 
                  level = "level",
                }
              }
            }

            stage.label_drop {
              values = [ "job", "service_name" ]
            }
          }

          loki.write "local" {
            endpoint {
              url = "http://loki-gateway/loki/api/v1/push"
              tenant_id = "1"
            }
          }

          loki.echo "example" { }
