apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft-server
nameSuffix: -atm10-server
resources:
  - namespace.yaml
  - ../../base/mc-atm
  - secret.yaml

patchesStrategicMerge:
  - patch-env.yaml