apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pyroscope
spec:
  interval: 30m
  chart:
    spec:
      chart: pyroscope
      version: "0.2.92"
      sourceRef:
        kind: HelmRepository
        name: pyroscope-charts
      interval: 12h

