apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 1h0m
  url: https://github.com/cloudnative-pg/cloudnative-pg
  ref:
    tag:  v1.26.0
