# Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-install
  namespace: flux-system
spec:
  interval: 10m
  path: ./releases
  prune: true
  sourceRef:
    kind: GitRepository
    name: cnpg
  targetNamespace: cnpg-system
  wait: true
  timeout: 5m
