apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-hole
  namespace: pi-hole
  labels:
    app: pi-hole
spec:
  selector:
    matchLabels:
      app: pi-hole
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pi-hole
    spec:
      containers:
        - name: pi-hole
          image: pihole/pihole:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
          volumeMounts:
            - name: pi-hole-pvc
              mountPath: /etc/pihole
            - name: pi-hole-pvc
              mountPath: /etc/dnsmasq.d
      volumes:
        - name: pi-hole-pvc
          persistentVolumeClaim:
            claimName: pi-hole-pvc
      restartPolicy: Always
