apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-pvc
  namespace: pi-hole
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  
