apiVersion: v1
kind: Service
metadata:
  name: pi-hole
  namespace: pi-hole
spec:
  selector:
    app: pi-hole
  ports:
    - port: 8080
      name: web
      targetPort: 80
    - port: 53
      name: dns
      targetPort: 53
      protocol: TCP
    - port: 53
      name: dns-udp
      targetPort: 53
      protocol: UDP
