apiVersion: v1
kind: Service
metadata:
  name: habitat-backend
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: habitat-backend
  ports:
  - port: 4000
    targetPort: 4000
  type: LoadBalancer