apiVersion: apps/v1
kind: Deployment
metadata:
  name: habitat-backend
spec:
  selector:
    matchLabels:
      app: habitat-backend
  template:
    metadata:
      labels:
        app: habitat-backend
    spec:
      imagePullSecrets:
        - habitat-backend-pull
      containers:
      - name: habitat-backend
        image: mustybatz/habitat-backend
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
