apiVersion: apps/v1
kind: Deployment
metadata:
  name: habitat-backend
spec:
  selector:
    matchLabels:
      app: habitat-backend
  template:
    metadata:
      labels:
        app: habitat-backend
    spec:
      imagePullSecrets:
        - name: habitat-backend-pull
      containers:
        - name: habitat-backend
          image: mustybatz/habitat-backend:dev-43bf5b29-1749671221
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
          args:
            - "-host=$(HOST)"
            - "-port=$(DB_PORT)"
            - "-db_user=$(DB_USER)"
            - "-db_name=$(DB_NAME)"
            - "-backend_host=$(BACKEND_HOST)"
          env:
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: habitat-backend-config
                  key: host
            - name: DB_PORT
              value: "5432"  # or use configMap if dynamic
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: habitat-backend-config
                  key: db_user
            - name: DB_NAME
              value: "habitat_db"
            - name: BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: habitat-backend-config
                  key: backend_host
          volumeMounts:
            - name: secrets-volume
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: secrets-volume
          secret:
            secretName: habitat-backend-secrets
