apiVersion: v1
kind: Service
metadata:
  name: habitat-frontend
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: habitat-frontend
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
