apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - generate-classes-cronjob.yaml
