apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        fsGroup: 104
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8096
              name: http-tcp
              protocol: TCP
            - containerPort: 8920
              name: https-tcp
              protocol: TCP
            - containerPort: 1900
              name: dlna-udp
              protocol: UDP
            - containerPort: 7359
              name: discovery-udp
              protocol: UDP
          resources:
            limits:
              memory: "3Gi"
              cpu: "5"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: cache-volume
              mountPath: /cache
            - name: media-volume
              mountPath: /media
            - mountPath: /dev/dri
              name: jellyfin-hardware
          securityContext:
            privileged: true
          
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: cache-volume
          persistentVolumeClaim:
            claimName: jellyfin-cache
        - name: media-volume
          hostPath:
            path: /etc/media
            type: Directory
        - name: jellyfin-hardware
          hostPath:
            path: /dev/dri
