apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - namespace.yaml
  - helm-repository.yaml
  - mariadb-operator-crds-release.yaml
  - mariadb-operator-release.yaml