apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: flux-system  # Or another namespace if needed
spec:
  releaseName: mariadb-operator-crds
  chart:
    spec:
      chart: mariadb-operator-crds
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
  interval: 5m
