apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: flux-system  # Adjust namespace if necessary
spec:
  releaseName: mariadb-operator
  chart:
    spec:
      chart: mariadb-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
  interval: 5m
