apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: habitat-dev
resources:
  - ../../base/habitat
  - db.yaml
images:
  - name: mustybatz/habitat-backend
    newName: mustybatz/habitat-backend # {"$imagepolicy": "flux-system:habitat-backend-latest:name"}
    newTag: dev-fc7d314d-1750098818 # {"$imagepolicy": "flux-system:habitat-backend-latest:tag"}
  - name: keylab/habitat-frontend
    newName: keylab/habitat-frontend # {"$imagepolicy": "flux-system:habitat-frontend-latest:name"}
    newTag: dev-2be504d0-1749671128 # {"$imagepolicy": "flux-system:habitat-frontend-latest:tag"}
