apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: habitat-dev
resources:
  - ../../base/habitat
  - db.yaml
  - tunnel-binding.yaml
images:
  - name: mustybatz/habitat-backend
    newName: mustybatz/habitat-backend # {"$imagepolicy": "flux-system:habitat-backend-latest:name"}
    newTag: dev-dae0bc67-1757793952 # {"$imagepolicy": "flux-system:habitat-backend-latest:tag"}
  - name: keylab/habitat-frontend
    newName: keylab/habitat-frontend # {"$imagepolicy": "flux-system:habitat-frontend-latest:name"}
    newTag: dev-0f042077-1757792011 # {"$imagepolicy": "flux-system:habitat-frontend-latest:tag"}
