apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: mc
          image: itzg/minecraft-server
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
            - name: SPAWN_PROTECTION
              value: "1"
            - name: INIT_MEMORY
              value: "5G"
            - name: MAX_MEMORY
              value: "14G"
          resources:
            requests:
              memory: "5Gi"
              cpu: "1"
            limits:
              memory: "14G"
              cpu: "4"
          volumeMounts:
            - name: mc-data
              mountPath: /data

        - name: mc-backups
          image: itzg/mc-backup
          env:
            - name: BACKUP_INTERVAL
              value: "2h"
            - name: RCON_HOST
              value: "localhost"
            - name: MOTD
              value: "Welcum! UwU"
            - name: PRE_BACKUP_SCRIPT
              value: |
                echo "Before backup!"
                echo "Also before backup from $$RCON_HOST to $$DEST_DIR"
          resources:
            limits:
              memory: "1Gi"
              cpu: "200m"
          volumeMounts:
            - name: mc-data
              mountPath: /data
              readOnly: true
            - name: mc-backups
              mountPath: /backups

      volumes:
        - name: mc-data
          persistentVolumeClaim:
            claimName: minecraft-data
        - name: mc-backups
          persistentVolumeClaim:
            claimName: minecraft-backups-pvc
