apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-atm10-uwu
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-backups-pv-atm10-uwu
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mc-backups
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backups-pvc-atm10-uwu
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
