apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: linkding-tunnel
  namespace: linkding
subjects:
  - name: linkding
tunnelRef:
  kind: ClusterTunnel
  name: k3s-cluster-tunnel