apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: mc
          image: itzg/minecraft-server
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
            - name: SPAWN_PROTECTION
              value: "1"
            - name: MOTD
              value: "Welcome to Minecraft on Kubernetes"
            - name: MODPACK_PLATFORM
              value: "modrinth"
            - name: MODRINTH_MODPACK
              value: "aged"
            - name: VERSION
              value: LATEST
            - name: MODRINTH_IGNORE_MISSING_FILES
              value: config/mcinstanceloader/pack.mcinstance
          
          resources:
            requests:
              memory: "3Gi"
              cpu: "2"
            limits:
              memory: "5Gi"
              cpu: "4"
            
          volumeMounts:
            - name: mc-data
              mountPath: /data
      volumes:
        - name: mc-data
          persistentVolumeClaim:
            claimName: minecraft-data
