apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: mc
          image: itzg/minecraft-server
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
            - name: SPAWN_PROTECTION
              valueFrom:
                configMapKeyRef:
                  name: minecraft-config
                  key: spawn-protection
            - name: MOTD
              valueFrom:
                configMapKeyRef:
                  name: minecraft-config
                  key: motd
            - name: INIT_MEMORY
              valueFrom:
                configMapKeyRef:
                  name: minecraft-config
                  key: init-memory
            - name: MAX_MEMORY
              valueFrom:
                configMapKeyRef:
                  name: minecraft-config
                  key: max-memory
            - name: TYPE
              valueFrom:
                configMapKeyRef:
                  name: minecraft-config
                  key: server-type
            - name: VERSION
              valueFrom:
                configMapKeyRef:
                  name: minecraft-config
                  key: version
            - name: CF_PAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: minecraft-config
                  key: modpack-url
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: minecraft-config
                  key: cf-api-key
          resources:
            requests:
              memory: "6Gi"
              cpu: "2"
            limits:
              memory: "12Gi"
              cpu: "6"
            
          volumeMounts:
            - name: mc-data
              mountPath: /data

        - name: mc-backups
          image: itzg/mc-backup
          env:
            - name: BACKUP_INTERVAL
              value: "2h"
            - name: RCON_HOST
              value: "localhost"
            - name: MOTD
              value: "Welcome to FTB Evolution Server"
            - name: PRE_BACKUP_SCRIPT
              value: |
                echo "Starting backup of FTB Evolution server..."
                echo "Backing up from $$RCON_HOST to $$DEST_DIR"
          resources:
            limits:
              memory: "1Gi"
              cpu: "200m"
            requests:
              memory: "200Mi"
              cpu: "10m"
          volumeMounts:
            - name: mc-data
              mountPath: /data
            - name: mc-backups
              mountPath: /backups

      volumes:
        - name: mc-data
          persistentVolumeClaim:
            claimName: minecraft-data
        - name: mc-backups
          persistentVolumeClaim:
            claimName: minecraft-backups
