apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  annotations:
    longhorn.io/replica-count: "1"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backups
  annotations:
    longhorn.io/replica-count: "1"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
