apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
