apiVersion: apps/v1
kind: Deployment
metadata:
  name: librum
  namespace: librum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librum
  template:
    metadata:
      labels:
        app: librum
    spec:
      tolerations:
        - key: "node"
          operator: "Equal"
          value: "kthulu-deepone-worker-0"
          effect: "NoSchedule"
      nodeSelector:
        node: "kthulu-deepone-worker-0"
      containers:
        - name: librum
          image: ghcr.io/librum-reader/librum-server:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: librum-config
            - secretRef:
                name: librum-secrets
          volumeMounts:
            - name: librum-storage
              mountPath: /var/lib/librum-server/librum_storage
      volumes:
        - name: librum-storage
          persistentVolumeClaim:
            claimName: librum-storage
