apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: librum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      tolerations:
        - key: "node"
          operator: "Equal"
          value: "kthulu-deepone-worker-0"
          effect: "NoSchedule"
      nodeSelector:
        node: "kthulu-deepone-worker-0"
      containers:
        - name: mariadb
          image: mariadb:latest
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: librum-config
            - secretRef:
                name: librum-secrets
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
          startupProbe:
            exec:
              command:
                - mariadb-admin
                - ping
                - -u
                - librum
                - -p'mariadb'
                - -h
                - 127.0.0.1
            failureThreshold: 3
            periodSeconds: 20
            timeoutSeconds: 40
            initialDelaySeconds: 30
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-storage
