apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librum-storage
  namespace: librum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-storage
  namespace: librum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
