apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: librum
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: librum
  namespace: librum
spec:
  type: LoadBalancer
  selector:
    app: librum
  ports:
    - port: 5000
      targetPort: 5000
